import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      // Next.js expects layout.tsx to return only <html> and <body> tags at the root
      // Avoid using browser-only code or extensions that inject attributes
      <html lang="en">
        <body className="antialiased">
          {children}
        </body>
      </html>
  );
}
